pool:
  vmImage: windows-latest
pr:
  branches:
    include:
    - '*'
resources:
  repositories:
  - endpoint: simplic-bot
    name: simplic/build-infrastructure
    repository: infrastructure
    type: github
steps:
- inputs:
    versionSpec: 5.x
  task: NuGetToolInstaller@1
- inputs:
    command: restore
    feedsToUse: select
    restoreSolution: '**/*.sln'
    vstsFeed: f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e
  task: NuGetCommand@2
- inputs:
    configuration: $(buildConfiguration)
    solution: '**/*.sln'
  task: MSBuild@1
- ${{ if not(eq(variables['Build.Reason'], 'PullRequest')) }}:
  - parameters:
      branch_name: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '')
        }}
      connection_string: $(connection_string)
      git_pass: $(git_pass)
      git_user: $(git_user)
    template: version-number-update-template.yml@infrastructure
- inputs:
    testAssemblyVer2: '**\Simplic.Authorization.Test.dll

      !**\*TestAdapter.dll

      !**\obj\**

      '
    testSelector: testAssemblies
  task: VSTest@2
- inputs:
    command: pack
    configuration: $(buildConfiguration)
    packagesToPack: simplic-authorization/Simplic.Authorization**/*.csproj;!simplic-authorization/Simplic.Authorization.Test/Simplic.Authorization.Test.csproj
    versioningScheme: 'off'
  task: NuGetCommand@2
- condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    allowPackageConflicts: true
    command: push
    nuGetFeedType: internal
    packagesToPush: $(Build.ArtifactStagingDirectory)/Simplic.Authorization.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.Authorization.*.symbols.nupkg
    publishVstsFeed: f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e
  task: NuGetCommand@2
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/*
    - azure-pipelines.yml
variables:
  buildConfiguration: Release
